package main

import "testing"

func TestD08P1(t *testing.T) {
	input := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

	expected := 14

	if v := d08p1(input); v != expected {
		t.Errorf("expcted %v, got %v", expected, v)
	}
}

func TestD08P2(t *testing.T) {
	input := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

	expected := 34

	if v := d08p2(input); v != expected {
		t.Errorf("expcted %v, got %v", expected, v)
	}
}
